/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ZontabPrivacyRouteImport } from './routes/zontab-privacy'
import { Route as IndexRouteImport } from './routes/index'

const ZontabPrivacyRoute = ZontabPrivacyRouteImport.update({
  id: '/zontab-privacy',
  path: '/zontab-privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/zontab-privacy': typeof ZontabPrivacyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/zontab-privacy': typeof ZontabPrivacyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/zontab-privacy': typeof ZontabPrivacyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/zontab-privacy'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/zontab-privacy'
  id: '__root__' | '/' | '/zontab-privacy'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ZontabPrivacyRoute: typeof ZontabPrivacyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/zontab-privacy': {
      id: '/zontab-privacy'
      path: '/zontab-privacy'
      fullPath: '/zontab-privacy'
      preLoaderRoute: typeof ZontabPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ZontabPrivacyRoute: ZontabPrivacyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
