/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ZontabSupportRouteImport } from './routes/zontab-support'
import { Route as ZontabPrivacyRouteImport } from './routes/zontab-privacy'
import { Route as PsxLensRouteImport } from './routes/psx-lens'
import { Route as IndexRouteImport } from './routes/index'

const ZontabSupportRoute = ZontabSupportRouteImport.update({
  id: '/zontab-support',
  path: '/zontab-support',
  getParentRoute: () => rootRouteImport,
} as any)
const ZontabPrivacyRoute = ZontabPrivacyRouteImport.update({
  id: '/zontab-privacy',
  path: '/zontab-privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PsxLensRoute = PsxLensRouteImport.update({
  id: '/psx-lens',
  path: '/psx-lens',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/psx-lens': typeof PsxLensRoute
  '/zontab-privacy': typeof ZontabPrivacyRoute
  '/zontab-support': typeof ZontabSupportRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/psx-lens': typeof PsxLensRoute
  '/zontab-privacy': typeof ZontabPrivacyRoute
  '/zontab-support': typeof ZontabSupportRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/psx-lens': typeof PsxLensRoute
  '/zontab-privacy': typeof ZontabPrivacyRoute
  '/zontab-support': typeof ZontabSupportRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/psx-lens' | '/zontab-privacy' | '/zontab-support'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/psx-lens' | '/zontab-privacy' | '/zontab-support'
  id: '__root__' | '/' | '/psx-lens' | '/zontab-privacy' | '/zontab-support'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PsxLensRoute: typeof PsxLensRoute
  ZontabPrivacyRoute: typeof ZontabPrivacyRoute
  ZontabSupportRoute: typeof ZontabSupportRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/zontab-support': {
      id: '/zontab-support'
      path: '/zontab-support'
      fullPath: '/zontab-support'
      preLoaderRoute: typeof ZontabSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zontab-privacy': {
      id: '/zontab-privacy'
      path: '/zontab-privacy'
      fullPath: '/zontab-privacy'
      preLoaderRoute: typeof ZontabPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/psx-lens': {
      id: '/psx-lens'
      path: '/psx-lens'
      fullPath: '/psx-lens'
      preLoaderRoute: typeof PsxLensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PsxLensRoute: PsxLensRoute,
  ZontabPrivacyRoute: ZontabPrivacyRoute,
  ZontabSupportRoute: ZontabSupportRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
